services:
  vote:
    build: ./vote
    container_name: vote-js
    ports:
      - "5000:5000"

  result:
    build: ./result
    container_name: python-app
    ports:
      - "5001:4000"
    depends_on:
      - db

  redis:
    image: "redis:alpine"
    container_name: redis-db
    expose:
      - "6379"
    ports:
      - "6379:6379"
    depends_on:
      - db

  worker:
    build: ./worker
    container_name: worker-.net
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    build: ./postgres
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres